export * from "./interfaces/IAds";
export * from "./interfaces/IAnalytics";
export * from "./interfaces/IPlatform";
export * from "./interfaces/IRemoteConfig";
export * from "./interfaces/IShare";
export * from "./interfaces/IStorage";
export * from "./browser";
export * from "./capacitor";
export * from "./facebookInstant";
